# Generated by Django 3.2 on 2021-04-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id',
            new_name='uuid',
        ),
    ]
