# Generated by Django 3.2 on 2021-04-29 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
